#32 Development of matching logic
olegdavimuka/proj-pb14-course-project-group-2 pull request #39
Opened 2023-12-09 14:12 UTC by tnstsmsk

з правками враховуючи коменти 
https://github.com/olegdavimuka/proj-pb14-course-project-group-2/pull/36

2023-12-10 13:00 UTC, tnstsmsk commented
але єдине що в мене постійно вибиває помилку Rate limit reached for organization org-v8MaU4EwMUVTSvH2EBqR3s5P on requests per min (RPM): Limit 3, Used 3, Requested 1. 
Знайшла, що це можна пофіксити, якщо додати спроби і паузи між ними - але все рівно через раз працює 
Не зовсім розумію як це можна виправити

2023-12-11 11:41 UTC, olegdavimuka requested changes

2023-12-11 11:41 UTC, olegdavimuka commented on app/db/matching_logic.py
> +matched_users = find_matches(session)
логічніше буде передати тут список юзерів

2023-12-11 11:41 UTC, olegdavimuka commented on app/db/matching_logic.py
> +from models.user import User
Це скорше має бути в папці gpt, папка db для конфыгурацыы пыдключення до бд

2023-12-11 11:41 UTC, olegdavimuka commented on app/db/matching_logic.py
> +session = Session()
сесія створюється один раз, у цьому проекті ця логіка розміщена в db/database.py, її потрібно імпортувати звідти. Такий код як зараз скорше за все працювати не буде

2023-12-11 11:41 UTC, olegdavimuka commented on app/gpt/matching_logic.py
> +def find_matches(users):
Мені здається що цю логіку було б добре трішки переробити. Ти відправляєш окремий запит для кожного з юзерів, якщо в тебе буде наприклад 10000 юзерів, бо тобі потрібно буде відпарвити 10000 запитів, при тому що гпт обробляє їх поступово, то це займа дуже багато часу.

Також, друга проблема в тому про що ти якраз писала в коментарі до пул ріквесті - багато різних API мають обмеження на кількість запитів за певний час. Так як в гпт є і безкоштовна і платна версії, то скорше за все в платній або не буде обмежень на відправку запитів, або вони будуть більші.

Думаю, краще буде запускати або один запит передаючи в ньому список користувачів, або для кожного міста коремо, або для кожних 100 людей, або для одного міста і одних інтересів, тощо. В будь якому випадку основна суть в тому, щоб зменишти кількість запитав

2023-12-12 16:20 UTC, tnstsmsk commented
але промт постійно дає різні результати і я вже перепробувала різні підходи і структури коду 
адже окрім конкретних пар він дає ще купу лівого тексту

2023-12-13 09:57 UTC, olegdavimuka commented
> але промт постійно дає різні результати і я вже перепробувала різні підходи і структури коду адже окрім конкретних пар він дає ще купу лівого тексту

Тут я навскидку бачу 2 варіанти вирішення проблеми: перший - змінити сам промпт щоб він видавав лише пари, другий - парсити з відповіді самі пари. Тобто, опускати всі слова  окрім імен, які ми самі йому передали

2023-12-13 10:10 UTC, olegdavimuka commented
> > але промт постійно дає різні результати і я вже перепробувала різні підходи і структури коду адже окрім конкретних пар він дає ще купу лівого тексту
> 
> Тут я навскидку бачу 2 варіанти вирішення проблеми: перший - змінити сам промпт щоб він видавав лише пари, другий - парсити з відповіді самі пари. Тобто, опускати всі слова окрім імен, які ми самі йому передали

Передивився код, в загальному так, це приблизно те що я і мав на увазі. Основний нюанс в тому, що потрібно GPT використовувати як проміжну ланку, а потім його результати вже використувати щоб витягнути з бази реальних юзерів і їх зметчити. На сьогодні я думаю можемо ось так залишити, це більш менш робочий варіант, так як залишилось небагато часу було б круто встигнути ще доробити логіку реєстрації і це все разом повʼязати - щоб метчінг тягнув юзерів з бази і цим юзерам розсилав сповіщення.

2023-12-13 10:10 UTC, olegdavimuka approved these changes

2023-12-13 10:10 UTC, merged